name: My CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run script file
        run: ./test.sh
        shell: bash


  push_commit:
    needs: [run_script]
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v3

#      - name: Add & Commit changes
#      - uses: EndBug/add-and-commit@v7
#        with:
#          default_author: github_actions
#          message: 'Automated report 1'

#      - name: Create report file
#        run: date +%s > report.txt
      - name: Commit report
        uses: actions/checkout@v3
        run: |
#          git config --global user.name 'Your Name'
#          git config --global user.email 'your-username@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.MY_TOKEN }}@github.com/BezMan/Github-Actions
          git checkout "${GITHUB_REF:11}"
          git commit -am "Automated report 2"
          git push
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v3
#
#      - name: Run Lint
#        run: ./gradlew lintDebug
#
#      - name: Upload html test report
#        uses: actions/upload-artifact@v3
#        with:
#          name: lint.html
#          path: app/build/reports/lint-results-debug.html
#  unit-test:
#    needs: [lint]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v3
#
#      - name: Run tests
#        run: ./gradlew test
#
#      - name: Upload test report
#        uses: actions/upload-artifact@v3
#        with:
#          name: unit_test_report
#          path: app/build/reports/tests/testDebugUnitTest/
#          cache: gradle
#
##  instrumentation-test:
##    needs: [unit-test]
##    runs-on: macos-latest
##    steps:
##      - name: Checkout the code
##        uses: actions/checkout@v3
##
##      - name: set up JDK 11
##        uses: actions/setup-java@v3
##        with:
##          java-version: 11
##
##      - name: Run espresso tests
##        uses: reactivecircus/android-emulator-runner@v2
##        with:
##          api-level: 29
##          script: ./gradlew connectedCheck
##
##      - name: Upload test report
##        uses: actions/upload-artifact@v3
##        with:
##          name: instrumentation_test_report
##          path: app/build/reports/androidTests/connected/
#
#  generate-apk:
##    needs: [instrumentation-test]
#    needs: [unit-test]
#    name: Generate APK
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v3
#
#      - name: Build debug APK
#        run: ./gradlew assembleDebug --stacktrace
#
#      - name: Upload APK
#        uses: actions/upload-artifact@v3
#        with:
#          name: app-apk.apk
#          path: app/build/outputs/apk/debug/app-debug.apk
