name: 2023 CI Push
on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]
  workflow_dispatch:

jobs:

  one-job-for-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload lint report
        uses: actions/upload-artifact@v3
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Upload unit test report
        uses: actions/upload-artifact@v3
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-apk.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Run script file - run unit tests
        run: ./unitTest.sh
        shell: bash
#
#      - name: Commit and Push changes
#        run: |
#          git config user.email "silverbez@gmail.com"
#          git config user.name "BezMan"
#          git remote set-url origin https://x-access-token:${{ secrets.MY_TOKEN }}@github.com/BezMan/Github-Actions
#          git add .
#          git commit -am "Automated report 2"
#          git push




#  instrumentation-test:
##    needs: [unit-test]
#    runs-on: macos-latest
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v3
#
#      - name: set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: 11
#
#      - name: Run espresso tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: ./gradlew connectedCheck
#
#      - name: Upload test report
#        uses: actions/upload-artifact@v3
#        with:
#          name: instrumentation_test_report
#          path: app/build/reports/androidTests/connected/
